import { User } from '../types';

export const mockUsers: User[] = [
  {
    id: 1,
    name: { first: 'John', last: 'Doe' },
    email: 'john.doe@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/1.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/1.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/1.jpg',
    },
    location: { city: 'New York', country: 'USA' },
    dob: { age: 28 },
    phone: '123-456-7890',
    cell: '123-456-7890',
    nat: 'US',
    gender: 'male',
    login: { uuid: '1' },
  },
  {
    id: 2,
    name: { first: 'Jane', last: 'Smith' },
    email: 'jane.smith@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/women/1.jpg',
      medium: 'https://randomuser.me/api/portraits/med/women/1.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/women/1.jpg',
    },
    location: { city: 'London', country: 'UK' },
    dob: { age: 24 },
    phone: '987-654-3210',
    cell: '987-654-3210',
    nat: 'GB',
    gender: 'female',
    login: { uuid: '2' },
  },
  {
    id: 3,
    name: { first: 'Michael', last: 'Johnson' },
    email: 'michael.johnson@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/2.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/2.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/2.jpg',
    },
    location: { city: 'Toronto', country: 'Canada' },
    dob: { age: 32 },
    phone: '555-123-4567',
    cell: '555-123-4567',
    nat: 'CA',
    gender: 'male',
    login: { uuid: '3' },
  },
  {
    id: 4,
    name: { first: 'Emily', last: 'Williams' },
    email: 'emily.williams@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/women/2.jpg',
      medium: 'https://randomuser.me/api/portraits/med/women/2.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
    },
    location: { city: 'Sydney', country: 'Australia' },
    dob: { age: 29 },
    phone: '444-555-6666',
    cell: '444-555-6666',
    nat: 'AU',
    gender: 'female',
    login: { uuid: '4' },
  },
  {
    id: 5,
    name: { first: 'David', last: 'Brown' },
    email: 'david.brown@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/3.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/3.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/3.jpg',
    },
    location: { city: 'Berlin', country: 'Germany' },
    dob: { age: 35 },
    phone: '111-222-3333',
    cell: '111-222-3333',
    nat: 'DE',
    gender: 'male',
    login: { uuid: '5' },
  },
  {
    id: 6,
    name: { first: 'Sarah', last: 'Miller' },
    email: 'sarah.miller@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/women/3.jpg',
      medium: 'https://randomuser.me/api/portraits/med/women/3.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/women/3.jpg',
    },
    location: { city: 'Paris', country: 'France' },
    dob: { age: 27 },
    phone: '777-888-9999',
    cell: '777-888-9999',
    nat: 'FR',
    gender: 'female',
    login: { uuid: '6' },
  },
  {
    id: 7,
    name: { first: 'Robert', last: 'Wilson' },
    email: 'robert.wilson@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/4.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/4.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/4.jpg',
    },
    location: { city: 'Tokyo', country: 'Japan' },
    dob: { age: 31 },
    phone: '222-333-4444',
    cell: '222-333-4444',
    nat: 'JP',
    gender: 'male',
    login: { uuid: '7' },
  },
  {
    id: 8,
    name: { first: 'Jennifer', last: 'Taylor' },
    email: 'jennifer.taylor@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/women/4.jpg',
      medium: 'https://randomuser.me/api/portraits/med/women/4.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/women/4.jpg',
    },
    location: { city: 'Rome', country: 'Italy' },
    dob: { age: 26 },
    phone: '666-777-8888',
    cell: '666-777-8888',
    nat: 'IT',
    gender: 'female',
    login: { uuid: '8' },
  },
  {
    id: 9,
    name: { first: 'William', last: 'Anderson' },
    email: 'william.anderson@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/5.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/5.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/5.jpg',
    },
    location: { city: 'Madrid', country: 'Spain' },
    dob: { age: 33 },
    phone: '999-000-1111',
    cell: '999-000-1111',
    nat: 'ES',
    gender: 'male',
    login: { uuid: '9' },
  },
  {
    id: 10,
    name: { first: 'Lisa', last: 'Thomas' },
    email: 'lisa.thomas@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/women/5.jpg',
      medium: 'https://randomuser.me/api/portraits/med/women/5.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/women/5.jpg',
    },
    location: { city: 'Moscow', country: 'Russia' },
    dob: { age: 30 },
    phone: '333-444-5555',
    cell: '333-444-5555',
    nat: 'RU',
    gender: 'female',
    login: { uuid: '10' },
  },

  {
    id: 50,
    name: { first: 'Daniel', last: 'Clark' },
    email: 'daniel.clark@example.com',
    picture: {
      large: 'https://randomuser.me/api/portraits/men/25.jpg',
      medium: 'https://randomuser.me/api/portraits/med/men/25.jpg',
      thumbnail: 'https://randomuser.me/api/portraits/thumb/men/25.jpg',
    },
    location: { city: 'Seoul', country: 'South Korea' },
    dob: { age: 34 },
    phone: '123-987-6543',
    cell: '123-987-6543',
    nat: 'KR',
    gender: 'male',
    login: { uuid: '50' },
  }
];